### DISCUSSION TITLE
Feature: add support for custom shell scripts

### DISCUSSION THREAD

**Discussion by Nopik** [martomi/chiadog#173] [Ideas]
E.g. I would wish to be able to define a number of scripts, each returning `0` or non-`0` process exit code, so Chiadog could run them occasionally and send notification when non-zero return code is seen.

Examples usage would be checking whether temperature is above threshold or disk space is below threshold etc. - in a pluginable way.

Alternatively, Chiadog could check the 2 conditions mentioned above, but over the time I would end up with much more checks.

**Comment by pieterhelsen** [comment]
I've taken a few first tiny steps towards implementing this feature. I'm thinking we should have the ability to run both local and remote scripts, so I've currently set up the config file as such:

```
custom_monitors:
  - name: 'CPU Temperatures'
    enable: true
    file_path: '/home/pi/myscript.sh'
    interval: 10
    remote:
      remote_host: '192.168.0.2'
      remote_user: 'pi'
  - name: 'Disk Usage'
    enable: true
    interval: 600
    file_path: 'c:\Users\Pi\myscript.ps1'
```

In terms of return signal, why not implement something a little more expressive such as a JSON string? 
That way you don't need to fill the config with notification messages. Would probably look something like this:

```
{ "event_priority": 0, "message": "CPU Core Temperature is currently above 75° (82.1°)" }
```

Chiadog would then take that event, slap a priority icon on it, append the monitor's `name` and send it off to one or more notifiers. 

Should each of these custom monitors live in its own separate thread?
