### DISCUSSION TITLE
[ WARNING] --- Cannot process user events: 0 notifiers are enabled! (notify_manager.py:52)

### DISCUSSION THREAD

**Discussion by krazy369** [martomi/chiadog#232] [Q&A]
Hi there, 

I have set the following in the config.yaml

  telegram:
    enable: true
    daily_stats: true
    wallet_events: true
    credentials:
      bot_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      chat_id: 'xxxxxxxxx'

but I got the error message [[ WARNING] --- Cannot process user events: 0 notifiers are enabled! (notify_manager.py:52)] when I start Chiadog every time and no telegram notification received so far.  

I have tried to restart the chiadog programme for many times but no luck.  Anyone knows what's wrong with the settings?  

Thank you for your help in advance!!

[Operating system: Windows 10]

**Comment by martomi** [comment]
Indentation matters:
```
notifier:
  telegram:
    enable: true
    daily_stats: true
    wallet_events: true
    credentials:
      bot_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      chat_id: 'xxxxxxxxx'
```
