### ISSUE TITLE
🚨 Chialog HARVESTER Your harvester appears to be offline! No events for the past 22200 seconds.

### ISSUE THREAD

**Issue by luisfgbb** [martomi/chiadog#229]
🚨 Chialog HARVESTER
Your harvester appears to be offline! No events for the past 22200 seconds.
I have already tried all the functions of #72 

yesterday I installed the latest version of Chia 1.1.7

any help for dummies?

**Environment:**
 - OS:  win 10
 - Python version: 3.9
 - PIP version:
 - Chia version: 1.1.7

**Comment by pieterhelsen** [comment]
What chiadog version are you on? 
`git describe --tags`

Also, when starting chiadog, do you get a message saying 'Farming with X plots'?
Please post this snippet from your chiadog config (make sure to leave out any identifiable information such as usernames or IP addresses):

```
chia_logs:
  file_log_consumer:
    enable: true
    file_path: 'C:\Users\REDACTED\workspace\debug.log'
  network_log_consumer:
    enable: false
    remote_file_path: "/home/REDACTED/.chia/mainnet/log/debug.log"
    remote_host: REDACTED
    remote_user: REDACTED
```
