### ISSUE TITLE
Docker Documentation

### ISSUE THREAD

**Issue by unintended-consequences** [martomi/chiadog#349]
I'm trying to spin up a new instance via docker-compose. There doesn't seem to be much documentation. 

Have tried the following:

`version: "3.7"

services:

  chiadog:
    image: "ghcr.io/martomi/chiadog:latest"
    container_name: "chiadog"
    volumes:
      - ~/chiadog/config:/root/.chia
    environment:
      - TZ=$TZ`

I've put a config.yaml into the config folder but I am getting this error:

`/chiadog/venv/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "/chiadog/main.py", line 112, in <module>
    conf = Config(Path(args.config))
  File "/chiadog/src/config.py", line 14, in __init__
    raise ValueError(f"Invalid config.yaml path: {config_path}")
ValueError: Invalid config.yaml path: /root/.chiadog/config.yaml`

**Comment by unintended-consequences** [comment]
ha ok. Should be .chiadog in docker-compose file. Will clean this up.

**Comment by unintended-consequences** [comment]
Have tried mapping known_hosts to:

/etc/ssh
/root/.ssh

Docker container itself works as I can get the file_log_consumer to run. But the network_log_consumer is not a happy bunny.

**Comment by djerfy** [comment]
@unintended-consequences your server is already in your known_hosts file?

**Comment by andrius-nordcode** [comment]
@unintended-consequences this is docker-compose.yml that works for me

```
version: "3"
services:
    chiadog:
        image: 'ghcr.io/martomi/chiadog:latest'
        container_name: chiadog
        volumes:
            - ~/.config/chiadog/:/root/.chiadog/
            - ~/.chia/mainnet/log/:/root/.chia/mainnet/log:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
```
